log:
  level: INFO
http:
  port: 8080
  read-timeout: 10s
  write-timeout: 10s
  max-header-megabytes: 1
db:
  host: <host>
  port: <port>
  name: <db name>
  user: <username>
  password: <password>
  ssl-mode: <mode>
auth:
  access-token-ttl: 15m
  refresh-token-ttl: 1h
  refresh-token-length: 0
  password-salt: <salt>
  jwt:
    key: <key>
account:
  card-cash-limit: 0
  loan-deposit-limit: 0